import type { CollectionConfig } from 'payload'
import { aiLocalizeCollection } from '../hooks/aiLocalize'

export const Commitments: CollectionConfig = {
  slug: 'commitments',
  labels: {
    singular: 'Commitment',
    plural: 'Commitments',
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['key', 'title', 'category', 'impact_score', 'updatedAt'],
    group: 'Reference Data',
  },

  access: {
    read: () => true, // public read
  },

  fields: [
    {
      name: 'stableId',
      type: 'text',
      label: 'Stable ID',
      required: true,
      unique: true,
      localized: false,
      admin: {
        readOnly: true,
        condition: (_, siblingData) => !siblingData?.id,
        description: 'Autogenerated UUID; do not edit. Used to match D1 table rows.',
      },
    },
    {
      name: 'key',
      type: 'text',
      required: true,
      unique: true,
      localized: false,
      admin: {
        description: 'Machine key (e.g. no_pesticides, plant_native_flowers)',
      },
    },
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
      admin: {
        description: 'Human-readable label (localized).',
      },
    },
    {
      name: 'description',
      type: 'textarea',
      localized: true,
    },
    {
      name: 'emoji',
      type: 'text',
      localized: false,
      required: false,
      admin: {
        description: 'Single emoji character (optional)',
      },
      validate: (value) => {
        if (!value) return true // optional field
        // Regex to match a single emoji (including multi-codepoint emojis)
        const emojiRegex = /^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)$/u
        if (!emojiRegex.test(value)) {
          return 'Please enter a valid emoji character'
        }
        return true
      },
    },
    {
      name: 'category',
      type: 'text',
      localized: false,
      admin: {
        description: 'e.g. planting, maintenance, water, nesting',
      },
    },
    {
      name: 'impact_score',
      type: 'number',
      min: 0,
      max: 100,
      localized: false,
      admin: {
        description: 'Rough impact score 0-100',
      },
    },
    {
      name: 'seasonal_start_month',
      type: 'number',
      min: 1,
      max: 12,
      localized: false,
      admin: {
        description: 'Month when this commitment becomes relevant (1-12)',
      },
    },
    {
      name: 'seasonal_end_month',
      type: 'number',
      min: 1,
      max: 12,
      localized: false,
      admin: {
        description: 'Month when this commitment ends (1-12)',
      },
    },
    {
      name: 'repeat_interval_days',
      type: 'number',
      localized: false,
      admin: {
        description: 'NULL for one-off, or number of days between repetitions (e.g. 30)',
      },
    },
    {
      name: 'space_types',
      type: 'relationship',
      relationTo: 'space-types',
      hasMany: true,
      required: true,
      localized: false,
      admin: {
        description: 'Space types this commitment applies to',
      },
    },
  ],

  hooks: {
    beforeValidate: [
      ({ data }) => {
        if (!data.stableId) data.stableId = crypto.randomUUID()
      },
    ],
    beforeChange: [
      ({ data, originalDoc }) => {
        if (originalDoc?.stableId && data?.stableId !== originalDoc.stableId) {
          data.stableId = originalDoc.stableId
        }
      },
    ],
    afterChange: [
      aiLocalizeCollection(
        {
          baseURL: 'https://api.deepseek.com',
          apiKey: process.env.DEEPSEEK_API_KEY!,
          model: 'deepseek-chat',
          temperature: 0.2,
          maxTokens: 500,
        },
        {
          fields: ['title', 'description'],
          guardFlagField: 'autoLocalize',
        },
      ),
    ],
  },
}
