/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    'in-app-notifications': InAppNotification;
    'action-cards': ActionCard;
    questionnaire: Questionnaire;
    badges: Badge;
    'space-reviews': SpaceReview;
    'push-notifications': PushNotification;
    'space-types': SpaceType;
    commitments: Commitment;
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'space-types': {
      commitments: 'commitments';
    };
  };
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'in-app-notifications': InAppNotificationsSelect<false> | InAppNotificationsSelect<true>;
    'action-cards': ActionCardsSelect<false> | ActionCardsSelect<true>;
    questionnaire: QuestionnaireSelect<false> | QuestionnaireSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    'space-reviews': SpaceReviewsSelect<false> | SpaceReviewsSelect<true>;
    'push-notifications': PushNotificationsSelect<false> | PushNotificationsSelect<true>;
    'space-types': SpaceTypesSelect<false> | SpaceTypesSelect<true>;
    commitments: CommitmentsSelect<false> | CommitmentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr' | 'de';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-filled from Title if left blank.
   */
  slug?: string | null;
  heroImage?: (number | null) | Media;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  actionButton?: string | null;
  actionButtonLink?: string | null;
  publishDate?: string | null;
  author?: string | null;
  reviewStatus?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-app-notifications".
 */
export interface InAppNotification {
  id: number;
  title: string;
  message: string;
  image?: (number | null) | Media;
  actionButtonText?: string | null;
  actionButtonLink?: string | null;
  /**
   * Add tags to categorize this notification.
   */
  tags?: string[] | null;
  /**
   * This note will not be displayed or used in the application but is a note for future reference as to the conditions under which this notification will be selected.
   */
  conditionNotes?: string | null;
  /**
   * The notification will only be displayed once this date is reached.
   */
  publishDate?: string | null;
  /**
   * The notification will not be displayed after this date.
   */
  endDate?: string | null;
  /**
   * The number of days between repeat displays. If set to 365, the user would receive the same message again next year.
   */
  schedule?: number | null;
  /**
   * Select the months that this notification is valid for.
   */
  validMonths?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12')[] | null;
  /**
   * Number of times a user can receive this message. When set to 1, the user will never see this notification again after the first display.
   */
  limmit?: number | null;
  key: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "action-cards".
 */
export interface ActionCard {
  id: number;
  title: string;
  slug: string;
  /**
   * Appears top left.
   */
  topic: string;
  /**
   * Appears top right.
   */
  tag: string;
  /**
   * A link to follow when the action cards is clicked.
   */
  link?: string | null;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishDate?: string | null;
  endDate?: string | null;
  /**
   * Show even if already viewed
   */
  multipleViews?: boolean | null;
  /**
   * Display this Action Card to all users. No rules will be checked before display
   */
  displayToAllUsers?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire".
 */
export interface Questionnaire {
  id: number;
  /**
   * This field is used to create the path but is not displayed in the app.
   */
  name: string;
  /**
   * this will be autogenerated based on the title.
   */
  slug: string;
  /**
   * This field is not displayed in the app.
   */
  note?: string | null;
  /**
   * A question card with a list of options.
   */
  questionCards?:
    | {
        title?: string | null;
        description?: string | null;
        allowMultiple?: boolean | null;
        options?:
          | {
              type: 'checkbox' | 'text' | 'number';
              description?: string | null;
              uuid: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * End screens that might be displayed. Add multiple if they react dynamically to the users options. include variables in curly braces for example "Hello {NAME}".
   */
  endScreens?:
    | {
        image?: (number | null) | Media;
        title: string;
        actionButton?: string | null;
        actionButtonLink?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        uuid: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  name: string;
  /**
   * Auto-filled from Name if left blank.
   */
  slug: string;
  icon?: (number | null) | Media;
  page: {
    title: string;
    description: string;
    image?: (number | null) | Media;
    actionButton?: string | null;
    actionButtonLink?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-reviews".
 */
export interface SpaceReview {
  id: number;
  /**
   * Human-readable name (localized).
   */
  label: string;
  description?: string | null;
  /**
   * This message will only be shown to users with these space types.
   */
  includedSpaceTypes?: (number | SpaceType)[] | null;
  /**
   * This message will only be shown to users who have these commitments.
   */
  includedCommitments?: (number | Commitment)[] | null;
  /**
   * This message will only be shown to users who do not have these commitments.
   */
  excludedCommitments?: (number | Commitment)[] | null;
  /**
   * Total number of commitments required to see this message
   */
  minCommitments?: number | null;
  /**
   * The Maximum number of commitments required to see this message
   */
  maxCommitments?: number | null;
  active?: boolean | null;
  /**
   * Machine identifier — must match D1.space_reviews.key
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-types".
 */
export interface SpaceType {
  id: number;
  /**
   * Commitments associated with this space type
   */
  commitments?: {
    docs?: (number | Commitment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Human-readable name (localized).
   */
  label: string;
  /**
   * The default image to display if the user has not yet uploaded an image.
   */
  defaultImage?: (number | null) | Media;
  /**
   * Single emoji character (optional)
   */
  emoji?: string | null;
  description?: string | null;
  sort?: number | null;
  active?: boolean | null;
  /**
   * Machine identifier (e.g. balcony, garden) — must match D1.space_types.key
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitments".
 */
export interface Commitment {
  id: number;
  /**
   * Human-readable label (localized).
   */
  title: string;
  description?: string | null;
  /**
   * Single emoji character (optional)
   */
  emoji?: string | null;
  /**
   * Rough impact score 0-100
   */
  impact_score?: number | null;
  /**
   * Space types this commitment applies to
   */
  space_types: (number | SpaceType)[];
  /**
   * Machine key (e.g. no_pesticides, plant_native_flowers)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notifications".
 */
export interface PushNotification {
  id: number;
  title: string;
  message: string;
  /**
   * To link to article use mybeehome://article/article-slug. To link to a questionnaire use mybeehome://questionnaire/questionnaire-slug
   */
  deepLink?: string | null;
  image?: (number | null) | Media;
  /**
   * Add tags to categorize this notification.
   */
  tags?: string[] | null;
  /**
   * This note will not be displayed or used in the application but is a note for future reference as to the conditions under which this notification will be selected.
   */
  conditionNotes?: string | null;
  /**
   * The notification will only be sent once this date is reached.
   */
  publishDate?: string | null;
  /**
   * When checked, the message will be sent to all users of the app. All conditional checks will be skipped and all users will receive the notification.
   */
  allUsers?: boolean | null;
  /**
   * Select the months that this notification is valid for.
   */
  validMonths?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12')[] | null;
  /**
   * The number of days between repeat sends. If set to 365, the user would receive the same message again next year.
   */
  schedule?: number | null;
  /**
   * Number of times a user can receive this message. When set to 1, the user will never be sent this notification again. Please note this does not include 'reads'. In other words, if sends is set to 8, the user will receive the message a maximum of 8 times, but only if they don't open it.
   */
  limmit?: number | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'in-app-notifications';
        value: number | InAppNotification;
      } | null)
    | ({
        relationTo: 'action-cards';
        value: number | ActionCard;
      } | null)
    | ({
        relationTo: 'questionnaire';
        value: number | Questionnaire;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'space-reviews';
        value: number | SpaceReview;
      } | null)
    | ({
        relationTo: 'push-notifications';
        value: number | PushNotification;
      } | null)
    | ({
        relationTo: 'space-types';
        value: number | SpaceType;
      } | null)
    | ({
        relationTo: 'commitments';
        value: number | Commitment;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  intro?: T;
  body?: T;
  actionButton?: T;
  actionButtonLink?: T;
  publishDate?: T;
  author?: T;
  reviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-app-notifications_select".
 */
export interface InAppNotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  image?: T;
  actionButtonText?: T;
  actionButtonLink?: T;
  tags?: T;
  conditionNotes?: T;
  publishDate?: T;
  endDate?: T;
  schedule?: T;
  validMonths?: T;
  limmit?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "action-cards_select".
 */
export interface ActionCardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  topic?: T;
  tag?: T;
  link?: T;
  image?: T;
  body?: T;
  publishDate?: T;
  endDate?: T;
  multipleViews?: T;
  displayToAllUsers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire_select".
 */
export interface QuestionnaireSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  note?: T;
  questionCards?:
    | T
    | {
        title?: T;
        description?: T;
        allowMultiple?: T;
        options?:
          | T
          | {
              type?: T;
              description?: T;
              uuid?: T;
              id?: T;
            };
        id?: T;
      };
  endScreens?:
    | T
    | {
        image?: T;
        title?: T;
        actionButton?: T;
        actionButtonLink?: T;
        body?: T;
        uuid?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  page?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        actionButton?: T;
        actionButtonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-reviews_select".
 */
export interface SpaceReviewsSelect<T extends boolean = true> {
  label?: T;
  description?: T;
  includedSpaceTypes?: T;
  includedCommitments?: T;
  excludedCommitments?: T;
  minCommitments?: T;
  maxCommitments?: T;
  active?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notifications_select".
 */
export interface PushNotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  deepLink?: T;
  image?: T;
  tags?: T;
  conditionNotes?: T;
  publishDate?: T;
  allUsers?: T;
  validMonths?: T;
  schedule?: T;
  limmit?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-types_select".
 */
export interface SpaceTypesSelect<T extends boolean = true> {
  commitments?: T;
  label?: T;
  defaultImage?: T;
  emoji?: T;
  description?: T;
  sort?: T;
  active?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitments_select".
 */
export interface CommitmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  emoji?: T;
  impact_score?: T;
  space_types?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}